spring:
  application:
    name: ForoHub
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate_sql: true

  server:
    error:
      include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET}